apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vault-autounseal-sealed.yaml

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.28.0
    releaseName: vault
    namespace: vault
    includeCRDs: true
    valuesFile: values.yaml