apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-server-tls
spec:
  secretName: argocd-server-tls
  issuerRef:
    name: argocd-issuer
    kind: Issuer
  commonName: argo.do.nullkarma.com
  dnsNames:
    - argo.do.nullkarma.com