{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "argocd-auth",
    "namespace": "argocd",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "argocd-auth",
        "namespace": "argocd",
        "creationTimestamp": null,
        "labels": {
          "app.kubernetes.io/part-of": "argocd"
        }
      }
    },
    "encryptedData": {
      "dex.github.clientSecret": "AgCZlDChTY19ozjDsk29UAxCN0uZL/sKPj4mIV2dcgICAIWfpIgRfypWbSCHpp5Q6ZXICF0y0MElW8YKFzPBlyPsV37DOZPTceWgG/V+Hha6BaCOwJ63klnC9yyrvTNipjeGUU1I8YLVCTtwCe+FcgesV9YFJc8Q/iuNbS7KeBWF78q1suT3nLxDG0ks3c2L5ibVrm4koQpr8uHJTv0MfmhyHsiryp23buudb85Zqh7UKMBDF0NGPAhJwNLDVASAlhYJ5h3kKPurZBhOkCMjhHF95LkLPWZ1LJF2m05LUYq9G71QvefEIlgb4IyUl1qgMdSthRDMh+/TrpNlg16AY0bx1Onsst04PA9u48bh2y3zysBRAG0u7mAZaENTYg3IQRlerKwxvadJ4+n8izTZqr26Z/pq/R9wFdPui1Pd6C/FXRvp9wqg0EWnpr7XHB77AqABuC8Tp7G4U0CZnGyrGnC/hkptWI0AK9xAUrZI45sL24EODdwrbisOrNSYVeMLYfUcGOFs0DdMCXpLR9QGM+s4qfk6IODswJTlGtSmnY4RoaKwBK4UIaF/vhJ3nk+67y8SgAan9ED5XyW3sGXrARYGcAB0dXlXiu4YLwzl3TuRq+eetrOZq5v6mAsmy2ZkDnELrqkztoi7Mldc0UO2VVJsfIcTvK5QNNoAn0DTmrDEuYRUX1JNubRx+9rX4Vm8f0hBjggHVF8E9X8OBee/+6J4MkMQtFIBupwFSPLtlfsaYaBP8gfwXH6O"
    }
  }
}
