ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    ingressClassResource:
      default: true
    service:
      type: LoadBalancer
      annotations:
        kubernetes.digitalocean.com/load-balancer-id: d05b77e4-df36-4dec-9c17-d733f69df40b
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 150Mi
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
