ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    ingressClassResource:
      default: true
    service:
      type: LoadBalancer
      annotations:
        kubernetes.digitalocean.com/load-balancer-id: 683b11b1-0a28-4db4-983f-708dd5ed932d
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 150Mi
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
