ingress-nginx:
  controller:
    extraArgs:
      enable-ssl-passthrough: ""
    ingressClassResource:
      default: true
    service:
      type: LoadBalancer
      annotations:
        kubernetes.digitalocean.com/load-balancer-id: 20587c8a-c7c3-4ad1-abf9-0cf5617933eb
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 500m
        memory: 150Mi
    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
