apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: '--enable-helm'
  url: "https://argo.do.nullkarma.com"
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: b97e44472275daadffc4
        clientSecret: $argocd-auth:dex.github.clientSecret
        orgs:
        - name: licketysplitops
          teams:
          - admins
    staticClients:
      - id: argo-workflows-sso
        name: Argo Workflow
        redirectURIs:
          - https://workflow.do.nullkarma.com/oauth2/callback
        secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET