apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../base

patches:
  - path: argocd-cm.yaml
  - path: argocd-rbac-cm.yaml
  - path: argocd-dex-deploy.yaml
