apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated: {}
  project: system
  source:
    repoURL: {{.Values.spec.source.repoURL}}
    targetRevision: {{.Values.spec.source.targetRevision}}
    path: manifests/sealed-secrets/base
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system