apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: argocd
  source:
    repoURL: {{.Values.spec.source.repoURL}}
    targetRevision: {{.Values.spec.source.targetRevision}}
    path: manifests/argocd/overlays
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd