apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  project: argocd
  source:
    path: manifests/argo-workflows/overlays
    repoURL: {{.Values.spec.source.repoURL}}
    targetRevision: {{.Values.spec.source.targetRevision}}
vision: dev
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
