apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  project: system
  source:
    repoURL: {{.Values.spec.source.repoURL}}
    targetRevision: {{.Values.spec.source.targetRevision}}
    path: manifests/cert-manager/base
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager